/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tour;

import Control.DAO_Tour;
import Object.Tour;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MYLAP.VN
 */
public class QuanLyTour extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyTour
     */
    private ArrayList<Tour> ListTour;
    DefaultTableModel model;

    public QuanLyTour() throws SQLException {
        initComponents();
        ListTour = new DAO_Tour().getListTour();
        model = (DefaultTableModel) TableTour.getModel();
        model.setColumnIdentifiers(new Object[]{"ma tour", "ten tour", "gia", "ngaybd", "ngaykt"});
        showtable();

        TableTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTourMouseClicked(evt);
            }
        });

        Entertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntertextActionPerformed(evt);
            }
        });
    }

  private void tableTourMouseClicked(java.awt.event.MouseEvent evt) {
    int selectedRow = TableTour.getSelectedRow(); // Lấy chỉ số dòng đã chọn

    // Kiểm tra xem có dòng nào được chọn không
    if (selectedRow != -1) {
        // Lấy dữ liệu từ hàng đã chọn và điền vào các trường nhập liệu
        txtMaTour.setText(model.getValueAt(selectedRow, 0).toString());
        txtTenTour.setText(model.getValueAt(selectedRow, 1).toString());
        txtGia.setText(model.getValueAt(selectedRow, 2).toString());

        // Định dạng ngày tháng năm
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Định dạng ngày từ cơ sở dữ liệu và mong muốn

        try {
            // Chuyển đổi ngày bắt đầu
            String ngayBDString = model.getValueAt(selectedRow, 3).toString();
            Date ngayBD = dateFormat.parse(ngayBDString);
            txtNgayBD.setDate(ngayBD);

            // Chuyển đổi ngày kết thúc
            String ngayKTString = model.getValueAt(selectedRow, 4).toString();
            Date ngayKT = dateFormat.parse(ngayKTString);
            txtNgayKT.setDate(ngayKT);
        } catch (Exception e) {
            e.printStackTrace(); // Xử lý ngoại lệ nếu có
        }
    } else {
        clearInputFields();
    }
}

    public void showtable() {
        for (Tour t : ListTour) {
            model.addRow(new Object[]{t.getMaTour(), t.getTenTour(), t.getGia(), t.getNgayBd(), t.getNgayKt()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        frame_category = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PageTour = new javax.swing.JLabel();
        PageKhachHang = new javax.swing.JLabel();
        PageHuongDanVien = new javax.swing.JLabel();
        PageDiemThamQuan = new javax.swing.JLabel();
        PageDatTour = new javax.swing.JLabel();
        frame_content = new javax.swing.JPanel();
        frame_nav = new javax.swing.JPanel();
        Entertext = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        frame_tbdata = new javax.swing.JScrollPane();
        TableTour = new javax.swing.JTable();
        frame_input = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtMaTour = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTenTour = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNgayBD = new com.toedter.calendar.JDateChooser();
        txtNgayKT = new com.toedter.calendar.JDateChooser();
        frame_btnfunction = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(906, 506));

        frame_category.setBackground(new java.awt.Color(0, 102, 102));
        frame_category.setPreferredSize(new java.awt.Dimension(200, 500));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Category");

        PageTour.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        PageTour.setForeground(new java.awt.Color(204, 204, 204));
        PageTour.setText("Tour");
        PageTour.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        PageTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PageTourMouseClicked(evt);
            }
        });

        PageKhachHang.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        PageKhachHang.setForeground(new java.awt.Color(204, 204, 204));
        PageKhachHang.setText("Khách hàng");
        PageKhachHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        PageKhachHang.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PageKhachHangAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        PageKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PageKhachHangMouseClicked(evt);
            }
        });

        PageHuongDanVien.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        PageHuongDanVien.setForeground(new java.awt.Color(204, 204, 204));
        PageHuongDanVien.setText("Hướng dẫn viên");
        PageHuongDanVien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        PageHuongDanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PageHuongDanVienMouseClicked(evt);
            }
        });

        PageDiemThamQuan.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        PageDiemThamQuan.setForeground(new java.awt.Color(204, 204, 204));
        PageDiemThamQuan.setText("Điểm tham quan");
        PageDiemThamQuan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        PageDiemThamQuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PageDiemThamQuanMouseClicked(evt);
            }
        });

        PageDatTour.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        PageDatTour.setForeground(new java.awt.Color(204, 204, 204));
        PageDatTour.setText("Đặt tour");
        PageDatTour.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        PageDatTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PageDatTourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frame_categoryLayout = new javax.swing.GroupLayout(frame_category);
        frame_category.setLayout(frame_categoryLayout);
        frame_categoryLayout.setHorizontalGroup(
            frame_categoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_categoryLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(frame_categoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PageTour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PageKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PageHuongDanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PageDiemThamQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PageDatTour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        frame_categoryLayout.setVerticalGroup(
            frame_categoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_categoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(PageTour)
                .addGap(18, 18, 18)
                .addComponent(PageKhachHang)
                .addGap(18, 18, 18)
                .addComponent(PageHuongDanVien)
                .addGap(18, 18, 18)
                .addComponent(PageDiemThamQuan)
                .addGap(18, 18, 18)
                .addComponent(PageDatTour)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frame_content.setPreferredSize(new java.awt.Dimension(700, 500));

        frame_nav.setBackground(new java.awt.Color(0, 144, 133));
        frame_nav.setPreferredSize(new java.awt.Dimension(700, 60));

        Entertext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Entertext.setBorder(null);
        Entertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntertextActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search_btn.png"))); // NOI18N
        btnSearch.setText("find");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frame_navLayout = new javax.swing.GroupLayout(frame_nav);
        frame_nav.setLayout(frame_navLayout);
        frame_navLayout.setHorizontalGroup(
            frame_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_navLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Entertext, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        frame_navLayout.setVerticalGroup(
            frame_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_navLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Entertext))
                .addGap(18, 18, 18))
        );

        frame_tbdata.setPreferredSize(new java.awt.Dimension(693, 281));

        TableTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tour", "Tên tour", "Giá", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ));
        frame_tbdata.setViewportView(TableTour);

        frame_input.setBackground(new java.awt.Color(204, 204, 204));
        frame_input.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        frame_input.setPreferredSize(new java.awt.Dimension(695, 90));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mã tour");

        txtMaTour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tên tour");

        txtTenTour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Ngày bắt đầu");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Ngày kết thúc");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Giá");

        txtNgayBD.setDateFormatString("yyyy-MM-dd\n");

        txtNgayKT.setDateFormatString("yyyy-MM-dd\n");

        javax.swing.GroupLayout frame_inputLayout = new javax.swing.GroupLayout(frame_input);
        frame_input.setLayout(frame_inputLayout);
        frame_inputLayout.setHorizontalGroup(
            frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_inputLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frame_inputLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(frame_inputLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        frame_inputLayout.setVerticalGroup(
            frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_inputLayout.createSequentialGroup()
                .addGroup(frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_inputLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frame_inputLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(frame_inputLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frame_inputLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        frame_btnfunction.setBackground(new java.awt.Color(204, 204, 204));
        frame_btnfunction.setPreferredSize(new java.awt.Dimension(695, 50));

        btnAdd.setBackground(new java.awt.Color(52, 103, 113));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(52, 103, 113));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Câp nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDel.setBackground(new java.awt.Color(52, 103, 113));
        btnDel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(52, 103, 113));
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame_btnfunctionLayout = new javax.swing.GroupLayout(frame_btnfunction);
        frame_btnfunction.setLayout(frame_btnfunctionLayout);
        frame_btnfunctionLayout.setHorizontalGroup(
            frame_btnfunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_btnfunctionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnAdd)
                .addGap(94, 94, 94)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnDel)
                .addGap(100, 100, 100)
                .addComponent(btnExit)
                .addGap(48, 48, 48))
        );
        frame_btnfunctionLayout.setVerticalGroup(
            frame_btnfunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_btnfunctionLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(frame_btnfunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDel)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        javax.swing.GroupLayout frame_contentLayout = new javax.swing.GroupLayout(frame_content);
        frame_content.setLayout(frame_contentLayout);
        frame_contentLayout.setHorizontalGroup(
            frame_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_contentLayout.createSequentialGroup()
                .addGroup(frame_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(frame_nav, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frame_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(frame_btnfunction, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(frame_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(frame_tbdata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(frame_input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frame_contentLayout.setVerticalGroup(
            frame_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frame_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frame_tbdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frame_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frame_btnfunction, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frame_category, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(frame_content, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(frame_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(frame_category, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntertextActionPerformed
        performSearch();
    }//GEN-LAST:event_EntertextActionPerformed

    private void performSearch() {
        String keyword = Entertext.getText().trim(); // Lấy từ khóa tìm kiếm từ ô nhập
        try {
            ListTour = new DAO_Tour().searchTour(keyword); // Tìm kiếm tour
            model.setRowCount(0); // Xóa bảng hiện tại
            showtable(); // Cập nhật bảng với kết quả tìm kiếm
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm tour!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Kiểm tra nếu có trường nào bị bỏ trống
    if (txtMaTour.getText().isEmpty() || txtTenTour.getText().isEmpty() || txtGia.getText().isEmpty()
            || txtNgayBD.getDate() == null || txtNgayKT.getDate() == null) {
        JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Tour t = new Tour();
    t.setMaTour(txtMaTour.getText());
    t.setTenTour(txtTenTour.getText());

    // Kiểm tra và thiết lập giá trị cho giá tour
    try {
        double gia = Double.parseDouble(txtGia.getText());
        if (gia <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Giá tour phải lớn hơn 0", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        t.setGia(gia);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Giá tour không hợp lệ. Vui lòng nhập số.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Định dạng ngày
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

    try {
        // Lấy và định dạng ngày bắt đầu
        Date ngaybdDate = txtNgayBD.getDate();
        String ngaybdStr = formatter.format(ngaybdDate);
        LocalDate ngaybd = LocalDate.parse(ngaybdStr);
        t.setNgayBd(ngaybd);

        // Lấy và định dạng ngày kết thúc
        Date ngayktDate = txtNgayKT.getDate();
        String ngayktStr = formatter.format(ngayktDate);
        LocalDate ngaykt = LocalDate.parse(ngayktStr);
        t.setNgayKt(ngaykt);

        // Kiểm tra xem ngày kết thúc có sau ngày bắt đầu không
        if (ngaykt.isBefore(ngaybd)) {
            JOptionPane.showMessageDialog(rootPane, "Ngày kết thúc phải sau ngày bắt đầu.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Định dạng ngày không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Thêm tour vào cơ sở dữ liệu
    try {
        if (new DAO_Tour().addTour(t)) {
            JOptionPane.showMessageDialog(rootPane, "Thêm tour thành công");
            // Sau khi thêm thành công, thêm tour vào danh sách và xóa các trường nhập
            ListTour.add(t);
            clearInputFields();
            TableTour.clearSelection();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Không thể thêm tour", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (SQLException ex) {
        Logger.getLogger(QuanLyTour.class.getName()).log(Level.SEVERE, null, ex);
    }

    showResult();
    TableTour.clearSelection();
    }//GEN-LAST:event_btnAddActionPerformed

    public void showResult() {
        Tour t = ListTour.get(ListTour.size() - 1);
        model.addRow(new Object[]{
            t.getMaTour(), t.getTenTour(), t.getGia(), t.getNgayBd(), t.getNgayKt()
        });
    }

    private void clearInputFields() {
    txtMaTour.setText("");
    txtTenTour.setText("");
    txtGia.setText("");
    txtNgayBD.setDate(null);
    txtNgayKT.setDate(null);
    txtMaTour.requestFocus(); // Đưa con trỏ về trường mã tour
    }


    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = TableTour.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một Tour để sửa.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Thu thập dữ liệu từ các trường nhập liệu
    String maTour = txtMaTour.getText().trim();
    String tenTour = txtTenTour.getText().trim();
    String giaStr = txtGia.getText().trim();
    
    if (maTour.isEmpty() || tenTour.isEmpty() || giaStr.isEmpty() || txtNgayBD.getDate() == null || txtNgayKT.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Định dạng ngày
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    // Xác thực và chuyển đổi giá từ String sang double
    double gia;
    try {
        gia = Double.parseDouble(giaStr);
        if (gia <= 0) {
            JOptionPane.showMessageDialog(this, "Giá phải là số dương.", "Lỗi Giá", JOptionPane.ERROR_MESSAGE);
            txtGia.requestFocus();
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Giá phải là số.", "Lỗi Giá", JOptionPane.ERROR_MESSAGE);
        txtGia.requestFocus();
        return;
    }

    // Xử lý ngày bắt đầu và ngày kết thúc
    LocalDate ngayBd = LocalDate.parse(new SimpleDateFormat("yyyy-MM-dd").format(txtNgayBD.getDate()));
    LocalDate ngayKt = LocalDate.parse(new SimpleDateFormat("yyyy-MM-dd").format(txtNgayKT.getDate()));

    if (ngayKt.isBefore(ngayBd)) {
        JOptionPane.showMessageDialog(this, "Ngày kết thúc không thể trước ngày bắt đầu.", "Lỗi Ngày", JOptionPane.ERROR_MESSAGE);
        txtNgayKT.requestFocus();
        return;
    }

    // Tạo đối tượng Tour đã cập nhật
    Tour updatedTour = new Tour();
    updatedTour.setMaTour(maTour);
    updatedTour.setTenTour(tenTour);
    updatedTour.setGia(gia);
    updatedTour.setNgayBd(ngayBd);
    updatedTour.setNgayKt(ngayKt);

    // Cập nhật đối tượng trong danh sách
    boolean isUpdated = DAO_Tour.updateTour(updatedTour);
    if (isUpdated) {
        // Cập nhật đối tượng trong danh sách và JTable
        ListTour.set(selectedRow, updatedTour);
        model.setValueAt(updatedTour.getMaTour(), selectedRow, 0);
        model.setValueAt(updatedTour.getTenTour(), selectedRow, 1);
        model.setValueAt(updatedTour.getGia(), selectedRow, 2);
        model.setValueAt(updatedTour.getNgayBd().format(formatter), selectedRow, 3);
        model.setValueAt(updatedTour.getNgayKt().format(formatter), selectedRow, 4);

        JOptionPane.showMessageDialog(this, "Sửa Tour thành công.", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        clearInputFields(); // Làm sạch các trường nhập liệu
    } else {
        JOptionPane.showMessageDialog(this, "Sửa Tour thất bại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUpdateActionPerformed


    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int selectedRow = TableTour.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một Tour để xóa.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Xác nhận lại với người dùng trước khi xóa
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa Tour này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return; // Nếu người dùng chọn "No", dừng thao tác xóa
        }

        String maTour = model.getValueAt(selectedRow, 1).toString();
        // Xóa tour khỏi danh sách ArrayList
        boolean isDeleted = DAO_Tour.deleteTour(maTour);
        if (isDeleted) {
            // Xóa tour khỏi danh sách ArrayList
            ListTour.remove(selectedRow);

            // Xóa hàng khỏi JTable
            model.removeRow(selectedRow);

            // Hiển thị thông báo đã xóa thành công
            JOptionPane.showMessageDialog(this, "Xóa Tour thành công.", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Xóa Tour thất bại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        clearInputFields();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        performSearch();
    }//GEN-LAST:event_btnSearchMouseClicked

    private void PageKhachHangAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PageKhachHangAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_PageKhachHangAncestorAdded


    private void PageKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PageKhachHangMouseClicked
        this.dispose();
        new QuanLyKhachHang().setVisible(true);
    }//GEN-LAST:event_PageKhachHangMouseClicked

    private void PageHuongDanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PageHuongDanVienMouseClicked

    }//GEN-LAST:event_PageHuongDanVienMouseClicked

    private void PageDiemThamQuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PageDiemThamQuanMouseClicked

    }//GEN-LAST:event_PageDiemThamQuanMouseClicked

    private void PageDatTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PageDatTourMouseClicked
        this.dispose();
        new booktour().setVisible(true);
    }//GEN-LAST:event_PageDatTourMouseClicked

    private void PageTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PageTourMouseClicked
        this.dispose();
        try {
            new QuanLyTour().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTour.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PageTourMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuanLyTour().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyTour.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Entertext;
    private javax.swing.JLabel PageDatTour;
    private javax.swing.JLabel PageDiemThamQuan;
    private javax.swing.JLabel PageHuongDanVien;
    private javax.swing.JLabel PageKhachHang;
    private javax.swing.JLabel PageTour;
    private javax.swing.JTable TableTour;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel frame_btnfunction;
    private javax.swing.JPanel frame_category;
    private javax.swing.JPanel frame_content;
    private javax.swing.JPanel frame_input;
    private javax.swing.JPanel frame_nav;
    private javax.swing.JScrollPane frame_tbdata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaTour;
    private com.toedter.calendar.JDateChooser txtNgayBD;
    private com.toedter.calendar.JDateChooser txtNgayKT;
    private javax.swing.JTextField txtTenTour;
    // End of variables declaration//GEN-END:variables
}
