/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tour;

import Control.DAO_TourDTQ;
import Control.DAO_TourHDV;
import Object.TourDTQ;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controller.tour_dtqlogic;

/**
 *
 * @author MYLAP.VN
 */
public class Tour_DTQ extends javax.swing.JInternalFrame {

    /**
     * Creates new form TourDTQ
     */
    
    private ArrayList<TourDTQ> listTourDTQ;
    private DefaultTableModel model;
    
    public Tour_DTQ() {
        initComponents();
        listTourDTQ = new DAO_TourDTQ().getAllTourDTQ();
        model = (DefaultTableModel) tableTourDTQ.getModel();
        
        
        // Tải dữ liệu ban đầu lên bảng
        loadData();
        
        // Sự kiện nhấp chuột để chọn hàng trong bảng
        tableTourDTQ.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tableDTQMouseClicked(evt);
            }
        });
    }
    
    private void loadData() {
        model.setRowCount(0); // Xóa dữ liệu cũ
        listTourDTQ =new DAO_TourDTQ().getAllTourDTQ();
        for (TourDTQ tdq : listTourDTQ) {
            model.addRow(new Object[]{tdq.getMaTour(), tdq.getMaDTQ()});
        }
    }

    private void tableDTQMouseClicked(MouseEvent evt) {
        int selectedRow = tableTourDTQ.getSelectedRow(); // Lấy chỉ số dòng được chọn
        if (selectedRow != -1) {
            // Lấy giá trị từ bảng và điền vào các trường nhập liệu
            String maTour = tableTourDTQ.getValueAt(selectedRow, 0).toString();
            String maDiemThamQuan = tableTourDTQ.getValueAt(selectedRow, 1).toString();
            
            txtMaTour.setText(maTour);
            txtMaDTQ.setText(maDiemThamQuan);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_nav = new javax.swing.JPanel();
        txtSearchDTQ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_searchtourdtq = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        frame_tbdata = new javax.swing.JScrollPane();
        tableTourDTQ = new javax.swing.JTable();
        frame_input = new javax.swing.JPanel();
        txtMaTour = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMaDTQ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        frame_btnfunction = new javax.swing.JPanel();
        btnAddTourDTQ = new javax.swing.JButton();
        btnUpdateTourDTQ = new javax.swing.JButton();
        btnXoaTourDTQ = new javax.swing.JButton();
        RefreshDTQ = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        frame_nav.setBackground(new java.awt.Color(76, 148, 189));
        frame_nav.setPreferredSize(new java.awt.Dimension(700, 60));

        txtSearchDTQ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchDTQ.setBorder(null);
        txtSearchDTQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDTQActionPerformed(evt);
            }
        });

        btn_searchtourdtq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search_btn.png"))); // NOI18N
        btn_searchtourdtq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_searchtourdtq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchtourdtqMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Tham quan địa danh");

        javax.swing.GroupLayout frame_navLayout = new javax.swing.GroupLayout(frame_nav);
        frame_nav.setLayout(frame_navLayout);
        frame_navLayout.setHorizontalGroup(
            frame_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_navLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchDTQ, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_searchtourdtq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(69, 69, 69))
        );
        frame_navLayout.setVerticalGroup(
            frame_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_navLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(frame_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btn_searchtourdtq)
                    .addComponent(jLabel7)
                    .addComponent(txtSearchDTQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        frame_tbdata.setPreferredSize(new java.awt.Dimension(693, 281));

        tableTourDTQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Tour", "Mã điểm tham quan"
            }
        ));
        frame_tbdata.setViewportView(tableTourDTQ);

        frame_input.setBackground(new java.awt.Color(204, 204, 204));
        frame_input.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        frame_input.setPreferredSize(new java.awt.Dimension(695, 90));

        txtMaTour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mã Tour");

        txtMaDTQ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mã DTQ");

        javax.swing.GroupLayout frame_inputLayout = new javax.swing.GroupLayout(frame_input);
        frame_input.setLayout(frame_inputLayout);
        frame_inputLayout.setHorizontalGroup(
            frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_inputLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaDTQ, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frame_inputLayout.setVerticalGroup(
            frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_inputLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(frame_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(txtMaDTQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        frame_btnfunction.setBackground(new java.awt.Color(204, 204, 204));
        frame_btnfunction.setPreferredSize(new java.awt.Dimension(695, 50));

        btnAddTourDTQ.setBackground(new java.awt.Color(52, 103, 113));
        btnAddTourDTQ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddTourDTQ.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTourDTQ.setText("Thêm");
        btnAddTourDTQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTourDTQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTourDTQActionPerformed(evt);
            }
        });

        btnUpdateTourDTQ.setBackground(new java.awt.Color(52, 103, 113));
        btnUpdateTourDTQ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateTourDTQ.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateTourDTQ.setText("Câp nhật");
        btnUpdateTourDTQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateTourDTQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTourDTQActionPerformed(evt);
            }
        });

        btnXoaTourDTQ.setBackground(new java.awt.Color(52, 103, 113));
        btnXoaTourDTQ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaTourDTQ.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTourDTQ.setText("Xóa");
        btnXoaTourDTQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaTourDTQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTourDTQActionPerformed(evt);
            }
        });

        RefreshDTQ.setBackground(new java.awt.Color(52, 103, 113));
        RefreshDTQ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RefreshDTQ.setForeground(new java.awt.Color(255, 255, 255));
        RefreshDTQ.setText("làm mới");
        RefreshDTQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RefreshDTQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshDTQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame_btnfunctionLayout = new javax.swing.GroupLayout(frame_btnfunction);
        frame_btnfunction.setLayout(frame_btnfunctionLayout);
        frame_btnfunctionLayout.setHorizontalGroup(
            frame_btnfunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_btnfunctionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddTourDTQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdateTourDTQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaTourDTQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RefreshDTQ)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frame_btnfunctionLayout.setVerticalGroup(
            frame_btnfunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_btnfunctionLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(frame_btnfunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTourDTQ)
                    .addComponent(btnUpdateTourDTQ)
                    .addComponent(btnXoaTourDTQ)
                    .addComponent(RefreshDTQ))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frame_nav, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
            .addComponent(frame_btnfunction, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
            .addComponent(frame_input, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
            .addComponent(frame_tbdata, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(frame_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frame_tbdata, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frame_input, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frame_btnfunction, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchDTQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDTQActionPerformed
        tour_dtqlogic logic = new tour_dtqlogic(tableTourDTQ, txtMaDTQ, txtMaTour, txtSearchDTQ, model);
        logic.performsearch();
    }//GEN-LAST:event_txtSearchDTQActionPerformed

    private void btnAddTourDTQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTourDTQActionPerformed
        tour_dtqlogic logic = new tour_dtqlogic(tableTourDTQ, txtMaDTQ, txtMaTour, txtSearchDTQ, model);
        logic.add_tourdtq_logic();
    }//GEN-LAST:event_btnAddTourDTQActionPerformed

    private void btnUpdateTourDTQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTourDTQActionPerformed
        tour_dtqlogic logic = new tour_dtqlogic(tableTourDTQ, txtMaDTQ, txtMaTour, txtSearchDTQ, model);
        logic.update_tourdtq_logic();
    }//GEN-LAST:event_btnUpdateTourDTQActionPerformed

    private void btnXoaTourDTQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTourDTQActionPerformed
        tour_dtqlogic logic = new tour_dtqlogic(tableTourDTQ, txtMaDTQ, txtMaTour, txtSearchDTQ, model);
        logic.delete_tourdtq_logic();
    }//GEN-LAST:event_btnXoaTourDTQActionPerformed

    private void RefreshDTQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshDTQActionPerformed
        tour_dtqlogic logic = new tour_dtqlogic(tableTourDTQ, txtMaDTQ, txtMaTour, txtSearchDTQ, model);
        logic.refresh_tourdtq();
    }//GEN-LAST:event_RefreshDTQActionPerformed

    private void btn_searchtourdtqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchtourdtqMouseClicked
        tour_dtqlogic logic = new tour_dtqlogic(tableTourDTQ, txtMaDTQ, txtMaTour, txtSearchDTQ, model);
        logic.performsearch();
    }//GEN-LAST:event_btn_searchtourdtqMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefreshDTQ;
    private javax.swing.JButton btnAddTourDTQ;
    private javax.swing.JButton btnUpdateTourDTQ;
    private javax.swing.JButton btnXoaTourDTQ;
    private javax.swing.JLabel btn_searchtourdtq;
    private javax.swing.JPanel frame_btnfunction;
    private javax.swing.JPanel frame_input;
    private javax.swing.JPanel frame_nav;
    private javax.swing.JScrollPane frame_tbdata;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTable tableTourDTQ;
    private javax.swing.JTextField txtMaDTQ;
    private javax.swing.JTextField txtMaTour;
    private javax.swing.JTextField txtSearchDTQ;
    // End of variables declaration//GEN-END:variables
}
